create_clock -period 25.000 -name clk -waveform {0.000 12.500} [get_ports clk]
create_clock -period 16.667 -name ft_clkout -waveform {0.000 8.333} [get_ports ft_clkout]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ft_clkout_IBUF]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_shdn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_shdn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_oe[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_oe[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_of[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_of[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {mix_enbl}]
set_property IOSTANDARD LVCMOS33 [get_ports {pa_off}]

set_property IOSTANDARD LVCMOS33 [get_ports {adf_muxout}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_le}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_ce}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_le}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_data}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_txdata}]
set_property IOSTANDARD LVCMOS33 [get_ports {adf_done}]

set_property IOSTANDARD LVCMOS33 [get_ports {sd_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_cmd}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_detect}]

set_property IOSTANDARD LVCMOS33 [get_ports {ext1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ext2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ft_oe}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_rd}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_siwua}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_wr}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_rxf}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_clkout}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_txe}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_suspend}]

set_property IOSTANDARD LVCMOS33 [get_ports {led}]

set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ft_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_din}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_dout}]



set_property PACKAGE_PIN N11 [get_ports clk]

set_property PACKAGE_PIN B1 [get_ports adc_shdn[0]]
set_property PACKAGE_PIN N2 [get_ports adc_shdn[1]]
set_property PACKAGE_PIN B2 [get_ports adc_oe[0]]
set_property PACKAGE_PIN P1 [get_ports adc_oe[1]]
set_property PACKAGE_PIN C2 [get_ports adc_of[0]]

set_property PACKAGE_PIN M1 [get_ports adc_of[1]]

set_property PACKAGE_PIN E2 [get_ports adc_d[11]]
set_property PACKAGE_PIN E1 [get_ports adc_d[10]]
set_property PACKAGE_PIN F2 [get_ports adc_d[9]]
set_property PACKAGE_PIN G1 [get_ports adc_d[8]]
set_property PACKAGE_PIN G2 [get_ports adc_d[7]]
set_property PACKAGE_PIN H3 [get_ports adc_d[6]]
set_property PACKAGE_PIN H2 [get_ports adc_d[5]]
set_property PACKAGE_PIN H1 [get_ports adc_d[4]]
set_property PACKAGE_PIN J3 [get_ports adc_d[3]]
set_property PACKAGE_PIN K1 [get_ports adc_d[2]]
set_property PACKAGE_PIN K2 [get_ports adc_d[1]]
set_property PACKAGE_PIN L2 [get_ports adc_d[0]]

set_property PACKAGE_PIN J4 [get_ports mix_enbl]
set_property PACKAGE_PIN T2 [get_ports pa_off]

set_property PACKAGE_PIN K3 [get_ports adf_muxout]
set_property PACKAGE_PIN N1 [get_ports adf_le]
set_property PACKAGE_PIN M2 [get_ports adf_data]
set_property PACKAGE_PIN R1 [get_ports adf_clk]
set_property PACKAGE_PIN P3 [get_ports adf_txdata]
set_property PACKAGE_PIN R3 [get_ports adf_ce]
set_property PACKAGE_PIN T4 [get_ports adf_done]

set_property PACKAGE_PIN N14 [get_ports sd_clk]
set_property PACKAGE_PIN R15 [get_ports sd_cmd]
set_property PACKAGE_PIN M16 [get_ports sd_data[3]]
set_property PACKAGE_PIN N16 [get_ports sd_data[2]]
set_property PACKAGE_PIN P16 [get_ports sd_data[1]]
set_property PACKAGE_PIN R16 [get_ports sd_data[0]]
set_property PACKAGE_PIN H16 [get_ports sd_detect]

set_property PACKAGE_PIN C16 [get_ports ft_suspend]
set_property PACKAGE_PIN D15 [get_ports ft_data[7]]
set_property PACKAGE_PIN D16 [get_ports ft_data[6]]
set_property PACKAGE_PIN E15 [get_ports ft_data[5]]
set_property PACKAGE_PIN E16 [get_ports ft_data[4]]
set_property PACKAGE_PIN F14 [get_ports ft_data[3]]
set_property PACKAGE_PIN G15 [get_ports ft_data[2]]
set_property PACKAGE_PIN G16 [get_ports ft_data[1]]
set_property PACKAGE_PIN F15 [get_ports ft_data[0]]

set_property PACKAGE_PIN B14 [get_ports ft_rd]
set_property PACKAGE_PIN A14 [get_ports ft_wr]
set_property PACKAGE_PIN A13 [get_ports ft_siwua]
set_property PACKAGE_PIN A12 [get_ports ft_oe]
set_property PACKAGE_PIN A15 [get_ports ft_clkout]
set_property PACKAGE_PIN B15 [get_ports ft_txe]
set_property PACKAGE_PIN B16 [get_ports ft_rxf]

set_property PACKAGE_PIN D1 [get_ports led]

set_property PACKAGE_PIN C11 [get_ports ext1[0]]
set_property PACKAGE_PIN B10 [get_ports ext1[1]]
set_property PACKAGE_PIN A9 [get_ports ext1[2]]
set_property PACKAGE_PIN C12 [get_ports ext1[3]]
set_property PACKAGE_PIN B9 [get_ports ext1[4]]
set_property PACKAGE_PIN A8 [get_ports ext1[5]]

set_property PACKAGE_PIN B7 [get_ports ext2[0]]
set_property PACKAGE_PIN A5 [get_ports ext2[1]]
set_property PACKAGE_PIN A4 [get_ports ext2[2]]
set_property PACKAGE_PIN A7 [get_ports ext2[3]]
set_property PACKAGE_PIN B5 [get_ports ext2[4]]
set_property PACKAGE_PIN A3 [get_ports ext2[5]]

set_property PACKAGE_PIN L12 [get_ports spi_cs]
set_property PACKAGE_PIN J14 [get_ports spi_din]
set_property PACKAGE_PIN J13 [get_ports spi_dout]

set_property PULLUP TRUE [get_ports adf_muxout]
set_property PULLUP TRUE [get_ports adf_done]
set_property PULLUP TRUE [get_ports sd_detect]